name: Update JSON file

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Setup python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.13'
    - run: pip install -r requirements.txt

    - name: Update JSON File
      run: |
        python script.py
    
    - name: Get current time and date
      id: date
      run: echo "date=$(date -u +'%Y/%m/%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT
    
    - name: Commit JSON to project
      uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
      with:
        commit_message: 'Update JSON file (${{ steps.date.outputs.date }})'
        branch: main
        commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"